Repository backube/volsync, pull requests merged in 2021-08, with the labels that each got.

#32 Fix codecov badge
  README.md
Labels: approved, lgtm, size/XS

#34 Fix import alias of core/v1 to always be corev1
  api/v1alpha1/replicationdestination_types.go
  api/v1alpha1/replicationsource_types.go
  controllers/mover/mover.go
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
  controllers/replicationdestination_test.go
  controllers/replicationsource_test.go
  controllers/utils/utils.go
  controllers/volumehandler.go
  controllers/volumehandler/new.go
  controllers/volumehandler/volumehandler.go
  controllers/volumehandler/volumehandler_test.go
Labels: approved, lgtm, size/L

#33 Fix restic test
  controllers/mover/restic/restic_test.go
  hack/run-in-kind.sh
  hack/run-minio.sh
Labels: approved, lgtm, size/XS

#37 Update codecov to not fail on poor coverage
  codecov.yml
Labels: approved, lgtm, size/XS

#36 Swap out Condition structures
  api/v1alpha1/common_types.go
  api/v1alpha1/replicationdestination_types.go
  api/v1alpha1/replicationsource_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/volsync.backube_replicationdestinations.yaml
  config/crd/bases/volsync.backube_replicationsources.yaml
  controllers/rclone_mover_test.go
  controllers/replicationdestination_controller.go
  controllers/replicationdestination_test.go
  controllers/replicationsource_controller.go
  go.mod
  go.sum
  helm/volsync/crds/volsync.backube_replicationdestinations.yaml
  helm/volsync/crds/volsync.backube_replicationsources.yaml
Labels: approved, lgtm, size/XL

#38 Updates for 0.3.0 release
  CHANGELOG.md
  helm/volsync/Chart.yaml
Labels: approved, lgtm, size/M

#40 Fix filename of svg logo
  docs/media/volsync.svg
Labels: lgtm, approved, size/XS

#42 Add ability to specify full container image in Chart
  helm/volsync/templates/_helpers.tpl
  helm/volsync/templates/deployment-controller.yaml
  helm/volsync/values.yaml
Labels: lgtm, approved, size/S

#47 Race in set-replication
  pkg/cmd/set_replication.go
Labels: lgtm, approved, size/M, ok-to-test

#43 Update readme
  Procedures.md
  README.md
Labels: lgtm, approved, size/L

#51 cli: set-replication doesn't obey source-name
  pkg/cmd/create_replication.go
  pkg/cmd/resource_options.go
  pkg/cmd/set_replication.go
Labels: lgtm, approved, size/L, ok-to-test

#53 cli should be usable w/o a config file
  docs/usage/rsync/db_example_cli.rst
  docs/usage/rsync/multi_context_sync_cli.rst
  docs/usage/rsync/plugin_opts.rst
  pkg/cmd/resource_options.go
  pkg/cmd/set_replication.go
  pkg/cmd/volsync.go
Labels: lgtm, approved, size/M

#55 Increase e2e timeout when waiting for snapshots
  test-kuttl/e2e/restic-with-manual-trigger/10-assert.yaml
  test-kuttl/e2e/restic-with-manual-trigger/20-assert.yaml
  test-kuttl/e2e/simple-rclone/10-create-destination.yaml
  test-kuttl/e2e/simple-rclone/16-assert.yaml
  test-kuttl/e2e/simple-rsync/15-create-source.sh
  test-kuttl/e2e/simple-rsync/30-assert.yaml
Labels: lgtm, approved, size/S

#65 Adds moving image tags for release & ocm branches
  .github/workflows/operator.yml
Labels: lgtm, approved, size/M
