Repository backube/volsync, pull requests merged in 2021-09, with the labels that each got.

#72 Add Kube 1.22 to the test matrix
  .github/workflows/operator.yml
  hack/setup-kind-cluster.sh
Labels: lgtm, approved, size/S

#45 Update Helm readme w/ description of *.image
  helm/volsync/README.md
Labels: lgtm, approved, size/S

#35 Replace utils.NameFor w/ client.ObjectKeyFromObject
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
  controllers/rclone_mover_test.go
  controllers/replicationdestination_controller.go
  controllers/replicationdestination_test.go
  controllers/replicationsource_controller.go
  controllers/replicationsource_test.go
  controllers/rsync_common.go
  controllers/utils/sahandler.go
  controllers/utils/utils.go
  controllers/volumehandler.go
  controllers/volumehandler/volumehandler.go
  controllers/volumehandler/volumehandler_test.go
Labels: lgtm, approved, size/L

#74 Build restic and rclone from source
  mover-rclone/Dockerfile
  mover-restic/Dockerfile
Labels: lgtm, approved, size/M

#56 Add more owners/reviewers
  OWNERS
Labels: lgtm, approved, size/XS, ok-to-test

#76 Adds Eventually Blocks To Rclone & Restic Tests
  controllers/mover/restic/restic_test.go
  controllers/rclone_mover_test.go
Labels: lgtm, approved, size/S

#81 Scaffold new CLI
  Makefile
  go.mod
  go.sum
  kubectl-volsync/cmd/client.go
  kubectl-volsync/cmd/cmd_suite_test.go
  kubectl-volsync/cmd/migration.go
  kubectl-volsync/cmd/migration_create.go
  kubectl-volsync/cmd/migration_delete.go
  kubectl-volsync/cmd/migration_rsync.go
  kubectl-volsync/cmd/relationship.go
  kubectl-volsync/cmd/relationship_test.go
  kubectl-volsync/cmd/root.go
  kubectl-volsync/main.go
Labels: lgtm, approved, size/XL

#80 Add VersionInfo to Builder interface
  controllers/mover/builder.go
  controllers/mover/restic/builder.go
  main.go
Labels: lgtm, approved, size/S

#87 Add parser for cross cluster resources
  kubectl-volsync/cmd/client.go
  kubectl-volsync/cmd/client_test.go
  kubectl-volsync/cmd/migration_create.go
Labels: lgtm, approved, size/M

#86 Add an ID to relationships
  go.mod
  kubectl-volsync/cmd/relationship.go
  kubectl-volsync/cmd/relationship_test.go
Labels: lgtm, approved, size/S

#91 Ensure golang modules are downloaded, not vendored
  Dockerfile
  Makefile
  mover-rclone/Dockerfile
  mover-restic/Dockerfile
Labels: lgtm, approved, size/XS

#92 Use ENV instead of ARG to override GOFLAGS
  Dockerfile
  mover-rclone/Dockerfile
  mover-restic/Dockerfile
Labels: lgtm, approved, size/XS
