Repository backube/volsync, pull requests merged in 2022-08, with the labels that each got.

#340 controller: Fix log timestamp format
  go.mod
  main.go
Labels: lgtm, approved, size/XS

#335 tests: Switch tests from kuttl to Ansible
  .ci-scripts/pre-commit.sh
  .ci-scripts/yamlconfig.yaml
  .github/dependabot.yml
  .github/workflows/operator.yml
  .gitignore
  test-e2e/Pipfile
  test-e2e/Pipfile.lock
  test-e2e/README.md
  test-e2e/ansible.cfg
  test-e2e/inventory.yml
  test-e2e/requirements.yml
  test-e2e/roles/compare_pvc_data/tasks/main.yml
  test-e2e/roles/create_namespace/handlers/main.yml
  test-e2e/roles/create_namespace/tasks/main.yml
  test-e2e/roles/create_rclone_secret/tasks/main.yml
  test-e2e/roles/gather_cluster_info/tasks/main.yml
  test-e2e/roles/get_minio_credentials/tasks/main.yml
  test-e2e/roles/write_to_pvc/tasks/main.yml
  test-e2e/run_tests_in_parallel.sh
  test-e2e/test_simple_rclone.yml
  test-e2e/test_simple_rsync.yml
Labels: lgtm, approved, size/XXL

#346 Tests: Dump logs playbook
  test-e2e/dump_logs.yml
  test-e2e/roles/dump_logs/tasks/dump_namespace_contents.yml
  test-e2e/roles/dump_logs/tasks/dump_volsync_logs.yml
  test-e2e/roles/dump_logs/tasks/main.yml
  test-e2e/run_tests_in_parallel.sh
Labels: lgtm, approved, size/M

#347 tests: Templatize Pods so they run as non-root on kube and OCP
  test-e2e/roles/compare_pvc_data/meta/main.yml
  test-e2e/roles/compare_pvc_data/tasks/main.yml
  test-e2e/roles/compare_pvc_data/templates/pod.yml.j2
  test-e2e/roles/write_to_pvc/meta/main.yml
  test-e2e/roles/write_to_pvc/tasks/main.yml
  test-e2e/roles/write_to_pvc/templates/pod.yml.j2
  test-e2e/test_simple_rclone.yml
  test-e2e/test_simple_rsync.yml
Labels: lgtm, approved, size/L

#356 tests: Use a smaller patch to connect syncthings
  test-e2e/roles/test_syncthing_cluster_sync/tasks/connect.yml
Labels: lgtm, approved, size/M

#354 Tests: Port over CLI tests
  test-e2e/roles/cli/handlers/main.yml
  test-e2e/roles/cli/tasks/main.yml
  test-e2e/roles/cli/tasks/setup.yml
  test-e2e/roles/compare_pvc_data/tasks/main.yml
  test-e2e/roles/compare_pvc_data/templates/pod.yml.j2
  test-e2e/roles/pvc_has_data/tasks/main.yml
  test-e2e/roles/pvc_has_data/templates/pod.yml.j2
  test-e2e/roles/write_to_pvc/templates/pod.yml.j2
  test-e2e/test_replication_sched_snap.yml
  test-e2e/test_replication_sync_direct.yml
  test-e2e/test_roles.yml
Labels: lgtm, approved, size/L

#359 tests: Allow overriding the command timeout for cli commands
  test-e2e/README.md
  test-e2e/roles/cli/tasks/main.yml
  test-e2e/test_replication_sched_snap.yml
  test-e2e/test_replication_sync_direct.yml
Labels: lgtm, approved, size/XS

#358 CI: Remove socat test pod from csi-hostpath in kind
  hack/setup-kind-cluster.sh
Labels: lgtm, approved, size/XS

#360 tests: Increase timeout waiting for syncthing pods to be deleted
  test-e2e/roles/test_syncthing_cluster_sync/tasks/main.yml
Labels: lgtm, approved, size/XS

#362 Use nodeSelector rather than nodeName to not bypass scheduler
  controllers/mover/rclone/mover.go
  controllers/mover/restic/mover.go
  controllers/mover/rsync/mover.go
  controllers/mover/syncthing/mover.go
  controllers/utils/affinity.go
  controllers/utils/affinity_test.go
Labels: lgtm, approved, size/M

#374 Update helm chart and manifests to deploy operator accd to pss/restricted
  .ci-scripts/retry.sh
  .github/workflows/operator.yml
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  controllers/utils/sahandler.go
  helm/volsync/templates/deployment-controller.yaml
  helm/volsync/values.yaml
  test-e2e/roles/dump_logs/tasks/dump_logs.yml
  test-e2e/roles/dump_logs/tasks/dump_namespace_contents.yml
  test-e2e/roles/dump_logs/tasks/dump_volsync_logs.yml
  test-e2e/roles/dump_logs/tasks/main.yml
  test-e2e/roles/pvc_has_data/tasks/main.yml
  test-e2e/roles/test_syncthing_cluster_sync/tasks/main.yml
  test-kuttl/cli/replication-sched-snap/01-label-namespace.yaml
  test-kuttl/cli/replication-sync-direct/01-label-namespace.yaml
  test-kuttl/e2e/multi-sync-snapshot-rclone/01-label-namespace.yaml
  test-kuttl/e2e/multi-sync-snapshot-restic/01-label-namespace.yaml
  test-kuttl/e2e/multi-sync-snapshot-rsync/01-label-namespace.yaml
  test-kuttl/e2e/restic-with-manual-trigger/01-label-namespace.yaml
  test-kuttl/e2e/restic-with-previous/01-label-namespace.yaml
  test-kuttl/e2e/restic-with-restoreasof/01-label-namespace.yaml
  test-kuttl/e2e/restic-without-trigger/01-label-namespace.yaml
  test-kuttl/e2e/simple-rclone/01-label-namespace.yaml
  test-kuttl/e2e/simple-rsync/01-label-namespace.yaml
  test-kuttl/e2e/syncthing-cluster-sync/01-label-namespace.yaml
Labels: lgtm, approved, size/L

#376 Backport fixes for PSS
  controllers/utils/sahandler.go
  helm/volsync/templates/deployment-controller.yaml
  helm/volsync/values.yaml
Labels: lgtm, approved, size/S

#388 restic: Dump the output of repo probe when we get an unexpected response
  mover-restic/entry.sh
Labels: lgtm, approved, size/XS

#391 restic: Patch restic to remove sha256-simd
  mover-restic/.gitignore
  mover-restic/Dockerfile
  mover-restic/README.md
  mover-restic/patch-sources.sh
Labels: lgtm, approved, size/M

#380 Version metadata to 0.6.0 in prep for next release
  bundle.Dockerfile
  bundle/manifests/volsync.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  version.mk
Labels: lgtm, approved, size/S

#397 syncthing: Disable use of minio's sha256-simd library
  mover-syncthing/entry.sh
Labels: lgtm, approved, size/XS

#387 Check for mover privilege annotation on ns and pass to movers
  api/v1alpha1/common_types.go
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/mover/builder.go
  controllers/mover/rclone/builder.go
  controllers/mover/rclone/rclone_test.go
  controllers/mover/restic/builder.go
  controllers/mover/restic/restic_test.go
  controllers/mover/rsync/builder.go
  controllers/mover/rsync/rsync_test.go
  controllers/mover/syncthing/builder.go
  controllers/mover/syncthing/syncthing_test.go
  controllers/replicationdestination_controller.go
  controllers/replicationsource_controller.go
  controllers/utils/namespace.go
  controllers/utils/namespace_test.go
  helm/volsync/templates/clusterrole-manager.yaml
Labels: lgtm, approved, size/L

#403 CI: Adjust test timeouts
  Makefile
  test-e2e/Pipfile.lock
  test-e2e/roles/compare_pvc_data/tasks/main.yml
  test-e2e/roles/pvc_affinity_pod/tasks/main.yml
  test-e2e/roles/pvc_has_data/tasks/main.yml
  test-e2e/roles/write_to_pvc/tasks/main.yml
  test-e2e/run_tests_in_parallel.sh
  test-e2e/test_multi_sync_snapshot_rclone.yml
  test-e2e/test_multi_sync_snapshot_rsync.yml
  test-e2e/test_replication_sched_snap.yml
  test-e2e/test_replication_sync_direct.yml
  test-e2e/test_restic_with_manual_trigger.yml
  test-e2e/test_restic_with_previous.yml
  test-e2e/test_restic_with_restoreasof.yml
  test-e2e/test_simple_rclone.yml
  test-e2e/test_simple_rsync.yml
Labels: lgtm, approved, size/L
