Repository backube/volsync, pull requests merged in 2022-03, with the labels that each got.

#142 CLI - Migration delete
  kubectl-volsync/cmd/migration.go
  kubectl-volsync/cmd/migration_delete.go
  kubectl-volsync/cmd/migration_delete_test.go
Labels: lgtm, approved, size/L

#156 Commit missed generated bundle scorecard config files
  .gitignore
  bundle/tests/scorecard/config.yaml
  config/scorecard/bases/config.yaml
Labels: lgtm, approved, size/M

#160 Add resources for submitting kubectl-volsync to krew
  .ci-scripts/yamlconfig.yaml
  .github/workflows/operator.yml
  Makefile
  kubectl-volsync/cmd/root.go
  kubectl-volsync/volsync.yaml
Labels: lgtm, approved, size/L

#166 Operator namespace
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/manifests/bases/volsync.clusterserviceversion.yaml
Labels: lgtm, approved, size/S

#169 Set 0.4.0 as bundle version, set channels in bundle metadata
  Makefile
  Procedures.md
  bundle.Dockerfile
  bundle/manifests/volsync.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  mover-rclone/Makefile
  mover-restic/Makefile
  mover-rsync/Makefile
  mover-syncthing/Makefile
  version.mk
Labels: lgtm, approved, size/L

#171 Check lastSyncStartTime in Eventually loop to avoid timing issues
  controllers/rclone_mover_test.go
Labels: lgtm, approved, size/XS

#173 Build docs on ocm- and release- branches as well as main
  .github/workflows/documentation.yml
Labels: lgtm, approved, size/XS

#180 tests: Add Eventually loop around lastSyncStartTime
  controllers/replicationdestination_test.go
  controllers/replicationsource_test.go
Labels: lgtm, approved, size/S

#178 Increase operator responsiveness
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/replicationdestination_controller.go
  controllers/replicationsource_controller.go
  hack/run-in-kind.sh
  helm/volsync/values.yaml
Labels: lgtm, approved, size/S

#168 Add syncthing mover build as dependency for e2e
  .github/workflows/operator.yml
Labels: lgtm, approved, size/XS

#181 Docs: RBAC to grant users access to VolSync CRs
  docs/installation/development.rst
  docs/installation/index.rst
  docs/installation/rbac.rst
Labels: lgtm, approved, size/L

#157 Document migration CLI sub-command
  bin/.keep
  bin/external-rsync-source
  docs/usage/cli/index.rst
  docs/usage/cli/migration.rst
  docs/usage/rsync/external_rsync.rst
Labels: lgtm, approved, size/L

#184 set minKubeVersion to 1.19.0 in CSV (added also to version.mk file)
  Makefile
  Procedures.md
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/manifests/bases/volsync.clusterserviceversion.yaml
  version.mk
Labels: lgtm, approved, size/XS

#185 Switch to snapshot.storage.k8s.io/v1
  .github/workflows/operator.yml
  CHANGELOG.md
  bundle/manifests/volsync.clusterserviceversion.yaml
  controllers/mover/rclone/mover.go
  controllers/mover/rclone/rclone_test.go
  controllers/mover/rclone/suite_test.go
  controllers/mover/restic/mover.go
  controllers/mover/restic/suite_test.go
  controllers/mover/rsync/mover.go
  controllers/mover/rsync/rsync_test.go
  controllers/mover/rsync/suite_test.go
  controllers/rclone_mover_test.go
  controllers/replicationdestination_controller.go
  controllers/replicationdestination_test.go
  controllers/replicationsource_controller.go
  controllers/replicationsource_test.go
  controllers/suite_test.go
  controllers/utils/cleanup.go
  controllers/volumehandler/suite_test.go
  controllers/volumehandler/volumehandler.go
  controllers/volumehandler/volumehandler_test.go
  go.mod
  go.sum
  hack/crds/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  hack/crds/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  hack/crds/snapshot.storage.k8s.io_volumesnapshots.yaml
  helm/volsync/Chart.yaml
  kubectl-volsync/cmd/suite_test.go
  main.go
  version.mk
Labels: lgtm, approved, size/XL

#159 Remove the old CLI
  cmd/volsync/volsync.go
  pkg/cmd/continue_replication.go
  pkg/cmd/create_replication.go
  pkg/cmd/options.go
  pkg/cmd/remove_replication.go
  pkg/cmd/resource_options.go
  pkg/cmd/set_replication.go
  pkg/cmd/sync_secret.go
  pkg/cmd/volsync.go
Labels: lgtm, approved, size/XXL

#189 Update kind to 0.12.0
  .github/workflows/operator.yml
  Procedures.md
  hack/setup-kind-cluster.sh
Labels: lgtm, approved, size/S

#121 Update kind cluster to use v5 of external-snapshotter
  hack/setup-kind-cluster.sh
Labels: lgtm, approved, size/S
