Repository backube/volsync, pull requests merged in 2022-04, with the labels that each got.

#195 Update apiVersion in rsync docs
  docs/usage/rsync/index.rst
Labels: lgtm, approved, size/XS, ok-to-test

#204 Add a check to make sure go.mod/sum is up-to-date
  .github/workflows/operator.yml
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#202 Add events to Rsync mover
  controllers/mover/events.go
  controllers/mover/mover.go
  controllers/mover/rclone/builder.go
  controllers/mover/restic/builder.go
  controllers/mover/rsync/builder.go
  controllers/mover/rsync/mover.go
  controllers/utils/utils.go
  controllers/volumehandler/new.go
  controllers/volumehandler/volumehandler.go
Labels: lgtm, approved, size/L

#205 Do not delete snap label
  controllers/mover/rclone/mover.go
  controllers/mover/restic/mover.go
  controllers/replicationdestination_controller.go
  controllers/utils/cleanup.go
  controllers/utils/cleanup_test.go
  controllers/utils/utils_suite_test.go
  controllers/volumehandler/volumehandler.go
  controllers/volumehandler/volumehandler_test.go
Labels: lgtm, approved, size/XL

#207 CLI: Properly overwrite deleted config options
  kubectl-volsync/cmd/relationship.go
Labels: lgtm, approved, size/S
