Repository backube/volsync, pull requests merged in 2022-10, with the labels that each got.

#407 Allow passing in GOOGLE_APPLICATION_CREDENTIALS
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
  docs/usage/restic/index.rst
Labels: lgtm, approved, size/L

#461 [release-0.5] Allow passing in GOOGLE_APPLICATION_CREDENTIALS
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
  docs/usage/restic/index.rst
Labels: lgtm, approved, size/L

#460 SA1019: package io/ioutil ...
  controllers/mover/rsync/rsync_common.go
  controllers/mover/syncthing/api/connection_utils.go
  kubectl-volsync/cmd/migration_create_test.go
  kubectl-volsync/cmd/migration_delete_test.go
  kubectl-volsync/cmd/migration_rsync.go
  kubectl-volsync/cmd/relationship_test.go
  kubectl-volsync/cmd/replication_test.go
Labels: lgtm, approved, size/M, ok-to-test

#462 Upgrade kube-rbac-proxy to v0.13.1
  CHANGELOG.md
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  helm/volsync/Chart.yaml
  helm/volsync/templates/deployment-controller.yaml
  test-e2e/Pipfile
  test-e2e/Pipfile.lock
Labels: lgtm, approved, size/M

#377 helm: Make chart manage VolSync CRDs
  .ci-scripts/pre-commit.sh
  CHANGELOG.md
  Makefile
  helm/volsync/Chart.yaml
  helm/volsync/README.md
  helm/volsync/crds/volsync.backube_replicationdestinations.yaml
  helm/volsync/crds/volsync.backube_replicationsources.yaml
  helm/volsync/templates/volsync.backube_replicationdestinations.yaml
  helm/volsync/templates/volsync.backube_replicationsources.yaml
  helm/volsync/values.yaml
Labels: lgtm, approved, size/XXL

#457 Cvp e2e test img (custom-scorecard-tests)
  .ci-scripts/yamlconfig.yaml
  .github/dependabot.yml
  .github/workflows/operator.yml
  Dockerfile.volsync-custom-scorecard-tests
  Makefile
  Procedures.md
  custom-scorecard-tests/README.md
  custom-scorecard-tests/config.yaml
  custom-scorecard-tests/generateE2ETestsConfig.sh
  custom-scorecard-tests/go.mod
  custom-scorecard-tests/go.sum
  custom-scorecard-tests/main.go
  custom-scorecard-tests/scorecard/bases/config.yaml
  custom-scorecard-tests/scorecard/kustomization.yaml
  custom-scorecard-tests/scorecard/patches/deploy-prereqs.yaml
  custom-scorecard-tests/scorecard/patches/e2e-tests.yaml
  hack/ensure-default-csi.sh
Labels: lgtm, approved, size/XXL

#439 changelog update for 0.5.1
  .ci-scripts/mdl-style.rb
  CHANGELOG.md
Labels: lgtm, approved, size/S

#426 Rclone: Add ability to run as non-root
  api/v1alpha1/replicationdestination_types.go
  api/v1alpha1/replicationsource_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/volsync.backube_replicationdestinations.yaml
  bundle/manifests/volsync.backube_replicationsources.yaml
  config/crd/bases/volsync.backube_replicationdestinations.yaml
  config/crd/bases/volsync.backube_replicationsources.yaml
  config/openshift/mover_scc.yaml
  controllers/mover/rclone/builder.go
  controllers/mover/rclone/mover.go
  controllers/mover/rclone/rclone_test.go
  controllers/mover/restic/mover.go
  controllers/mover/rsync/mover.go
  controllers/mover/rsync/rsync_common.go
  controllers/mover/rsync/rsync_test.go
  controllers/mover/syncthing/mover.go
  controllers/replicationdestination_test.go
  controllers/utils/sahandler.go
  helm/volsync/templates/SCC-mover.yaml
  helm/volsync/templates/volsync.backube_replicationdestinations.yaml
  helm/volsync/templates/volsync.backube_replicationsources.yaml
  mover-rclone/active.sh
  mover-rsync/Dockerfile
  mover-rsync/destination-command.sh
  mover-rsync/destination.sh
  test-e2e/test_rclone_normal.yml
  test-e2e/test_rclone_priv.yml
Labels: lgtm, approved, size/XXL

#476 [release-0.4] cherry-pick the mdl fixes
  .ci-scripts/mdl-style.rb
Labels: lgtm, approved, size/XS

#477 version 0.4.3 in release-0.4
  bundle/manifests/volsync.clusterserviceversion.yaml
  version.mk
Labels: lgtm, approved, size/S

#478 Golang1.18 for release-0.4
  .github/workflows/operator.yml
  Dockerfile
  Makefile
  controllers/mover/rclone/rclone_test.go
  controllers/mover/restic/restic_test.go
  controllers/mover/rsync/rsync_test.go
  go.mod
  go.sum
  mover-rclone/Dockerfile
  mover-restic/Dockerfile
Labels: lgtm, approved, size/L

#479 CI: Rename sonarcloud config
  .sonarcloud.properties
Labels: lgtm, approved, size/XS

#480 Reduced mover permissions for restic
  api/v1alpha1/common_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/replicationdestination_types.go
  api/v1alpha1/replicationsource_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/volsync.backube_replicationdestinations.yaml
  bundle/manifests/volsync.backube_replicationsources.yaml
  config/crd/bases/volsync.backube_replicationdestinations.yaml
  config/crd/bases/volsync.backube_replicationsources.yaml
  controllers/mover/restic/builder.go
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
  helm/volsync/templates/volsync.backube_replicationdestinations.yaml
  helm/volsync/templates/volsync.backube_replicationsources.yaml
  mover-restic/entry.sh
  test-e2e/test_restic_manual_normal.yml
  test-e2e/test_restic_manual_priv.yml
Labels: lgtm, approved, size/XXL
