Repository backube/volsync, pull requests merged in 2022-06, with the labels that each got.

#249 Update minio version
  hack/run-minio.sh
Labels: lgtm, approved, size/XS

#250 Set busybox imagePullPolicy to IfNotPresent
  test-kuttl/cli/replication-sched-snap/05-populate-source-volume.yaml
  test-kuttl/cli/replication-sched-snap/30-verify-data.yaml
  test-kuttl/cli/replication-sync-direct/05-populate-source-volume.yaml
  test-kuttl/cli/replication-sync-direct/07-set-affinity.yaml
  test-kuttl/cli/replication-sync-direct/30-verify-data.yaml
  test-kuttl/e2e/multi-sync-snapshot-rclone/05-populate-source-volume.yaml
  test-kuttl/e2e/multi-sync-snapshot-rclone/30-verify-data.yaml
  test-kuttl/e2e/multi-sync-snapshot-rclone/35-update-source-volume.yaml
  test-kuttl/e2e/multi-sync-snapshot-rclone/60-verify-data2.yaml
  test-kuttl/e2e/multi-sync-snapshot-restic/05-populate-source-volume.yaml
  test-kuttl/e2e/multi-sync-snapshot-restic/30-verify-data.yaml
  test-kuttl/e2e/multi-sync-snapshot-restic/35-update-source-volume.yaml
  test-kuttl/e2e/multi-sync-snapshot-restic/60-verify-data2.yaml
  test-kuttl/e2e/multi-sync-snapshot-rsync/05-populate-source-volume.yaml
  test-kuttl/e2e/multi-sync-snapshot-rsync/30-verify-data.yaml
  test-kuttl/e2e/multi-sync-snapshot-rsync/35-update-source-volume.yaml
  test-kuttl/e2e/multi-sync-snapshot-rsync/60-verify-data2.yaml
  test-kuttl/e2e/restic-with-manual-trigger/05-populate-source-volume.yaml
  test-kuttl/e2e/restic-with-manual-trigger/13-create-restore-volume.yaml
  test-kuttl/e2e/restic-with-manual-trigger/20-verify-data.yaml
  test-kuttl/e2e/restic-with-previous/05-populate-source-volume.yaml
  test-kuttl/e2e/restic-with-previous/13-create-restore-volume.yaml
  test-kuttl/e2e/restic-with-previous/20-verify-data-doesnt-match.yaml
  test-kuttl/e2e/restic-with-restoreasof/05-populate-source-volume.yaml
  test-kuttl/e2e/restic-with-restoreasof/13-create-restore-volume.yaml
  test-kuttl/e2e/restic-with-restoreasof/20-verify-data-doesnt-match.yaml
  test-kuttl/e2e/restic-with-restoreasof/23-verify-data.yaml
  test-kuttl/e2e/restic-with-restoreasof/25-write-new-data-to-source-volume.yaml
  test-kuttl/e2e/restic-with-restoreasof/50-verify-data-doesnt-match-current.yaml
  test-kuttl/e2e/restic-without-trigger/05-populate-source-volume.yaml
  test-kuttl/e2e/simple-rclone/04-populate-source-volume.yaml
  test-kuttl/e2e/simple-rclone/16-verify-data.yaml
  test-kuttl/e2e/simple-rsync/05-populate-source-volume.yaml
  test-kuttl/e2e/simple-rsync/30-verify-data.yaml
Labels: lgtm, approved, size/M

#241 Add sonarcloud configuration
  sonar-project.properties
Labels: lgtm, approved, size/S

#247 Update deps to kube 1.24
  go.mod
  go.sum
  kubectl-volsync/cmd/migration_create.go
Labels: lgtm, approved, size/L

#251 Pvc storage size - clone & snapshot - use capacity if possible
  controllers/volumehandler/volumehandler.go
  controllers/volumehandler/volumehandler_test.go
Labels: lgtm, approved, size/L

#260 Version operator to 0.4.1
  bundle/manifests/volsync.clusterserviceversion.yaml
  helm/volsync/Chart.yaml
  version.mk
Labels: lgtm, approved, size/S

#263 Update csv to v0.5.0 on stable,acm-2.6 channels
  CHANGELOG.md
  Procedures.md
  bundle.Dockerfile
  bundle/manifests/volsync.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  version.mk
Labels: lgtm, approved, size/S

#273 Update snapshot client to v6.0.1
  controllers/mover/rclone/mover.go
  controllers/mover/rclone/rclone_test.go
  controllers/mover/rclone/suite_test.go
  controllers/mover/restic/mover.go
  controllers/mover/restic/suite_test.go
  controllers/mover/rsync/mover.go
  controllers/mover/rsync/rsync_test.go
  controllers/mover/rsync/suite_test.go
  controllers/rclone_mover_test.go
  controllers/replicationdestination_controller.go
  controllers/replicationdestination_test.go
  controllers/replicationsource_controller.go
  controllers/replicationsource_test.go
  controllers/suite_test.go
  controllers/utils/cleanup.go
  controllers/utils/cleanup_test.go
  controllers/utils/utils_suite_test.go
  controllers/volumehandler/suite_test.go
  controllers/volumehandler/volumehandler.go
  controllers/volumehandler/volumehandler_test.go
  go.mod
  go.sum
  kubectl-volsync/cmd/suite_test.go
  main.go
Labels: lgtm, approved, size/M

#274 Upgrade operator-sdk to v1.22.0
  CHANGELOG.md
  Makefile
  Procedures.md
  bundle.Dockerfile
  bundle/manifests/volsync-manager-config_v1_configmap.yaml
  bundle/manifests/volsync.backube_replicationdestinations.yaml
  bundle/manifests/volsync.backube_replicationsources.yaml
  bundle/manifests/volsync.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/crd/bases/volsync.backube_replicationdestinations.yaml
  config/crd/bases/volsync.backube_replicationsources.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/controller_manager_config.yaml
  config/manager/manager.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  helm/volsync/Chart.yaml
  helm/volsync/crds/volsync.backube_replicationdestinations.yaml
  helm/volsync/crds/volsync.backube_replicationsources.yaml
  helm/volsync/templates/deployment-controller.yaml
  helm/volsync/values.yaml
  main.go
Labels: lgtm, approved, size/L

#281 Make sure cached client has label update before cleanup test
  controllers/mover/rsync/rsync_test.go
Labels: lgtm, approved, size/S

#293 Do not update running job.spec.template
  controllers/mover/rclone/mover.go
  controllers/mover/restic/mover.go
  controllers/mover/rsync/mover.go
  controllers/mover/rsync/rsync_test.go
Labels: lgtm, approved, size/L
