Repository backube/volsync, pull requests merged in 2022-05, with the labels that each got.

#210 Factor out the state machine
  Makefile
  api/v1alpha1/common_types.go
  controllers/metrics.go
  controllers/mover/builder.go
  controllers/rclone_mover_test.go
  controllers/replicationdestination_controller.go
  controllers/replicationdestination_test.go
  controllers/replicationsource_controller.go
  controllers/replicationsource_test.go
  controllers/statemachine/conditions.go
  controllers/statemachine/fake_machine.go
  controllers/statemachine/interface.go
  controllers/statemachine/machine.go
  controllers/statemachine/machine_test.go
  controllers/statemachine/suite_test.go
Labels: lgtm, approved, size/XXL

#212 Doc multiple pvcs per s3
  docs/usage/rclone/index.rst
  docs/usage/restic/database_example.rst
  docs/usage/restic/index.rst
  examples/rclone/volsync_v1alpha1_replicationdestination.yaml
  examples/rclone/volsync_v1alpha1_replicationsource.yaml
  hack/run-minio.sh
Labels: lgtm, approved, size/L

#214 Switch to upstream golang 1.17
  Dockerfile
  Makefile
  Procedures.md
  controllers/mover/rclone/rclone_test.go
  controllers/mover/restic/restic_test.go
  controllers/mover/rsync/rsync_test.go
  hack/run-in-kind.sh
  mover-rclone/Dockerfile
  mover-restic/Dockerfile
  mover-syncthing/Dockerfile
Labels: lgtm, approved, size/M

#203 Update to golang 1.18
  .github/workflows/operator.yml
  Dockerfile
  go.mod
  go.sum
  mover-rclone/Dockerfile
  mover-restic/Dockerfile
  mover-syncthing/Dockerfile
Labels: lgtm, approved, size/M

#215 Upgrade to operator-sdk v1.20.0
  Makefile
  bundle.Dockerfile
  bundle/manifests/volsync.backube_replicationdestinations.yaml
  bundle/manifests/volsync.backube_replicationsources.yaml
  bundle/manifests/volsync.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/crd/bases/volsync.backube_replicationdestinations.yaml
  config/crd/bases/volsync.backube_replicationsources.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  helm/volsync/crds/volsync.backube_replicationdestinations.yaml
  helm/volsync/crds/volsync.backube_replicationsources.yaml
  helm/volsync/templates/deployment-controller.yaml
  helm/volsync/values.yaml
Labels: lgtm, approved, size/L

#216 Metadata fixups for 0.4.0 release
  CHANGELOG.md
  helm/volsync/Chart.yaml
  kubectl-volsync/volsync.yaml
Labels: lgtm, approved, size/S

#218 Update docs to include CLI install via krew
  Procedures.md
  docs/usage/cli/index.rst
Labels: lgtm, approved, size/L

#219 Add kube 1.24 to test matrix
  .github/workflows/operator.yml
  hack/setup-kind-cluster.sh
Labels: lgtm, approved, size/S

#221 Use manual trigger in test to avoid multiple syncs during test
  controllers/replicationsource_test.go
Labels: lgtm, approved, size/XS

#220 Update utility dependencies
  CHANGELOG.md
  Makefile
  Procedures.md
  helm/volsync/Chart.yaml
  mover-rclone/Dockerfile
  mover-restic/Dockerfile
Labels: lgtm, approved, size/M

#224 Switch containers to ubi9
  Dockerfile
  mover-rclone/Dockerfile
  mover-restic/Dockerfile
  mover-rsync/Dockerfile
  mover-syncthing/Dockerfile
Labels: lgtm, approved, size/M

#225 Parallelize CI by separating unit tests
  .github/workflows/operator.yml
  Makefile
Labels: lgtm, approved, size/M

#228 Unpin sphinx-toolbox
  .github/workflows/documentation.yml
  docs/requirements.txt
  docs/setup-env.sh
Labels: lgtm, approved, size/XS

#227 Move kind to snapshotter v6 for 1.24+
  hack/setup-kind-cluster.sh
Labels: lgtm, approved, size/XS

#222 Add design doc for RWO mover affinity
  docs/design/index.rst
  docs/design/rwo-affinity.rst
  hack/run-minio.sh
Labels: lgtm, approved, size/L

#232 Enable dependabot updates
  .github/dependabot.yml
  .github/workflows/documentation.yml
  .github/workflows/operator.yml
Labels: lgtm, approved, size/M

#231 Switch relationship.go to yaml.v3
  go.mod
  kubectl-volsync/cmd/relationship.go
Labels: lgtm, approved, size/XS

#242 Upgrade operator-sdk to 1.21.0
  CHANGELOG.md
  Makefile
  bundle.Dockerfile
  bundle/manifests/volsync.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  controllers/suite_test.go
  go.mod
  go.sum
  helm/volsync/Chart.yaml
  helm/volsync/templates/deployment-controller.yaml
Labels: lgtm, approved, size/L
