Repository backube/volsync, pull requests merged in 2022-12, with the labels that each got.

#493 Syncthing - permission reduction
  api/v1alpha1/replicationsource_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/volsync.backube_replicationsources.yaml
  config/crd/bases/volsync.backube_replicationsources.yaml
  controllers/mover/syncthing/builder.go
  controllers/mover/syncthing/mover.go
  controllers/mover/syncthing/syncthing_test.go
  controllers/platform/properties_test.go
  custom-scorecard-tests/config.yaml
  custom-scorecard-tests/scorecard/patches/e2e-tests.yaml
  helm/volsync/templates/volsync.backube_replicationsources.yaml
  mover-syncthing/entry.sh
  test-e2e/roles/compare_pvc_data/tasks/main.yml
  test-e2e/roles/create_namespace/handlers/main.yml
  test-e2e/roles/create_namespace/tasks/main.yml
  test-e2e/roles/enable_privileged_mover/tasks/main.yml
  test-e2e/roles/mover_pod_is_privileged/tasks/main.yml
  test-e2e/roles/pvc_has_data/tasks/main.yml
  test-e2e/roles/test_roles/tasks/main.yml
  test-e2e/roles/test_syncthing_cluster_sync/tasks/await_connected.yml
  test-e2e/roles/test_syncthing_cluster_sync/tasks/connect.yml
  test-e2e/roles/test_syncthing_cluster_sync/tasks/kill_pods_by_label.yml
  test-e2e/roles/test_syncthing_cluster_sync/tasks/main.yml
  test-e2e/roles/write_to_pvc/tasks/main.yml
  test-e2e/test_syncthing_cluster_sync.yml
  test-e2e/test_syncthing_cluster_sync_normal.yml
  test-e2e/test_syncthing_cluster_sync_priv.yml
Labels: lgtm, approved, size/XXL

#515 Unit test fix - cleanup SCC crd in-between tests
  controllers/platform/properties_test.go
Labels: lgtm, approved, size/S

#520 [release-0.6] Unit test fix - cleanup SCC crd in-between tests
  controllers/platform/properties_test.go
Labels: lgtm, approved, size/S

#510 Add new rsync-tls mover
  .github/workflows/operator.yml
  mover-rsync-tls/Dockerfile
  mover-rsync-tls/Makefile
  mover-rsync-tls/client.sh
  mover-rsync-tls/server.sh
Labels: lgtm, approved, size/L

#517 CI: Enable periodic builds of release-0.6 branch
  .github/workflows/periodic.yml
Labels: lgtm, approved, size/XS

#521 Golang1.19 syncthing mover update
  .github/workflows/operator.yml
  CHANGELOG.md
  Dockerfile
  Dockerfile.volsync-custom-scorecard-tests
  Makefile
  Procedures.md
  controllers/mover/restic/suite_test.go
  controllers/mover/rsync/mover.go
  controllers/mover/syncthing/api/connection_utils.go
  controllers/mover/syncthing/mover.go
  controllers/platform/suite_test.go
  controllers/suite_test.go
  controllers/utils/affinity.go
  controllers/volumehandler/volumehandler.go
  custom-scorecard-tests/go.mod
  go.mod
  go.sum
  mover-rclone/Dockerfile
  mover-restic/Dockerfile
  mover-syncthing/Dockerfile
Labels: lgtm, approved, size/L

#524 Fix auto gen chck for release branches
  .github/workflows/operator.yml
  Makefile
  Procedures.md
Labels: lgtm, approved, size/S

#523 update cust scorecard config to use release-0.6 tags
  custom-scorecard-tests/config.yaml
  custom-scorecard-tests/scorecard/patches/deploy-prereqs.yaml
  custom-scorecard-tests/scorecard/patches/e2e-tests.yaml
Labels: lgtm, approved, size/M

#409 tests: Add support for running e2e in batches
  .github/workflows/operator.yml
  test-e2e/run_tests_in_parallel.sh
Labels: lgtm, approved, size/S, Stale

#532 e2e: Synchronously delete the Syncthing pods
  test-e2e/roles/test_syncthing_cluster_sync/tasks/kill_pods_by_label.yml
Labels: lgtm, approved, size/XS

#535 Update syncthing to 1.22.2
  go.mod
  go.sum
  mover-syncthing/Dockerfile
Labels: lgtm, approved, size/M

#536 Update rclone to v1.60.1
  mover-rclone/Dockerfile
Labels: lgtm, approved, size/XS

#540 CI: Add GH action to auto add new issues to project board
  .github/workflows/project-auto-add.yml
Labels: lgtm, approved, size/S

#483 CI: Don't fail if we can't upload coverage results
  .github/workflows/operator.yml
Labels: lgtm, approved, size/XS

#511 Add controller code for rsync-tls mover
  api/v1alpha1/replicationdestination_types.go
  api/v1alpha1/replicationsource_types.go
  api/v1alpha1/rsync_tls_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/volsync.backube_replicationdestinations.yaml
  bundle/manifests/volsync.backube_replicationsources.yaml
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/crd/bases/volsync.backube_replicationdestinations.yaml
  config/crd/bases/volsync.backube_replicationsources.yaml
  config/manager/kustomization.yaml
  config/openshift/mover_scc.yaml
  controllers/mover/rsynctls/builder.go
  controllers/mover/rsynctls/mover.go
  controllers/mover/rsynctls/rsync_common.go
  controllers/mover/rsynctls/rsync_test.go
  controllers/mover/rsynctls/suite_test.go
  custom-scorecard-tests/config.yaml
  custom-scorecard-tests/generateE2ETestsConfig.sh
  custom-scorecard-tests/scorecard/patches/e2e-tests.yaml
  hack/run-in-kind.sh
  helm/volsync/Chart.yaml
  helm/volsync/README.md
  helm/volsync/templates/deployment-controller.yaml
  helm/volsync/templates/volsync.backube_replicationdestinations.yaml
  helm/volsync/templates/volsync.backube_replicationsources.yaml
  helm/volsync/values.yaml
  main.go
  mover-rsync-tls/client.sh
  mover-rsync-tls/server.sh
  test-e2e/test_rsync_tls_normal.yml
  test-e2e/test_rsync_tls_priv.yml
Labels: lgtm, approved, size/XXL

#552 tests: Add retries to scorecard build
  Dockerfile.volsync-custom-scorecard-tests
Labels: lgtm, approved, size/S

#560 syncthing: ignore lost+found
  mover-syncthing/.stignore
  mover-syncthing/Dockerfile
  mover-syncthing/entry.sh
Labels: lgtm, approved, size/S

#551 CI: Add kube 1.26 to test matrix, update kind
  .github/workflows/operator.yml
  hack/setup-kind-cluster.sh
Labels: lgtm, approved, size/S

#559 e2e: Fix namespace role returning incorrect list of ns
  .github/workflows/operator.yml
  custom-scorecard-tests/config.yaml
  custom-scorecard-tests/scorecard/patches/e2e-tests.yaml
  test-e2e/roles/create_namespace/handlers/main.yml
  test-e2e/roles/create_namespace/tasks/main.yml
  test-e2e/test_namespace_role.yml
Labels: lgtm, approved, size/L

#516 rsync-tls: Add documentation for new rsync-tls mover
  docs/index.rst
  docs/usage/index.rst
  docs/usage/permissionmodel.rst
  docs/usage/rsync-tls/index.rst
  docs/usage/rsync-tls/mysql-migration.rst
  docs/usage/rsync/index.rst
Labels: lgtm, approved, size/XXL

#562 Update database_example.rst
  docs/usage/restic/database_example.rst
Labels: lgtm, approved, size/XS, ok-to-test
