Repository backube/volsync, pull requests merged in 2022-01, with the labels that each got.

#115 Adds Syncthing as a data mover in VolSync
  .github/workflows/operator.yml
  examples/syncthing/dokuwiki.yaml
  examples/syncthing/setup.sh
  examples/syncthing/syncthing.yaml
  mover-syncthing/Dockerfile
  mover-syncthing/Makefile
  mover-syncthing/config.xml
  mover-syncthing/entry.sh
Labels: lgtm, approved, size/XL

#122 CLI: create config directory if it doesn't exist
  kubectl-volsync/cmd/relationship.go
Labels: lgtm, approved, size/XS

#120 Refactor rsync to use mover interface
  controllers/mover/rsync/builder.go
  controllers/mover/rsync/mover.go
  controllers/mover/rsync/rsync_common.go
  controllers/mover/rsync/rsync_test.go
  controllers/mover/rsync/suite_test.go
  controllers/replicationdestination_controller.go
  controllers/replicationdestination_test.go
  controllers/replicationsource_controller.go
  controllers/replicationsource_test.go
  controllers/suite_test.go
  controllers/utils/utils.go
  controllers/volumehandler.go
  main.go
Labels: lgtm, approved, size/XXL

#124 Adding usage example for rsync in a cross cluster scenario
  docs/usage/rsync/database_example_cross_cluster.rst
  docs/usage/rsync/index.rst
  examples/rsync/volsync_v1alpha1_replicationdestination_remotecluster.yaml
  examples/rsync/volsync_v1alpha1_replicationsource_remotecluster.yaml
Labels: lgtm, approved, size/L

#133 Fix operator version embedding
  Dockerfile
  Makefile
Labels: lgtm, approved, size/XS

#131 Fixes for unit test flakes
  controllers/mover/rsync/rsync_test.go
  controllers/rclone_mover_test.go
  controllers/replicationdestination_test.go
  controllers/replicationsource_test.go
  kubectl-volsync/cmd/suite_test.go
  test-kuttl/e2e/restic-with-previous/20-assert.yaml
  test-kuttl/e2e/restic-with-previous/20-verify-data-doesnt-match.yaml
  test-kuttl/e2e/restic-with-restoreasof/20-assert.yaml
  test-kuttl/e2e/restic-with-restoreasof/20-verify-data-doesnt-match.yaml
  test-kuttl/e2e/restic-with-restoreasof/21-remove-restorecr-and-verify-job.yaml
  test-kuttl/e2e/restic-with-restoreasof/50-assert.yaml
  test-kuttl/e2e/restic-with-restoreasof/50-verify-data-doesnt-match-current.yaml
Labels: lgtm, approved, size/L
