Repository backube/volsync, pull requests merged in 2022-09, with the labels that each got.

#410 CI: Add kube 1.25 to test matrix + kind 0.15
  .github/workflows/operator.yml
  hack/setup-kind-cluster.sh
Labels: lgtm, approved, size/S

#406 rsync src mover - mount PVC as readOnly for ROX
  controllers/mover/rsync/mover.go
  controllers/utils/utils.go
  controllers/utils/utils_test.go
Labels: lgtm, approved, size/L

#413 Add package to detect platform properties
  .ci-scripts/yamlconfig.yaml
  bundle/manifests/volsync.backube_replicationdestinations.yaml
  bundle/manifests/volsync.backube_replicationsources.yaml
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/crd/bases/volsync.backube_replicationdestinations.yaml
  config/crd/bases/volsync.backube_replicationsources.yaml
  config/rbac/role.yaml
  controllers/platform/properties.go
  controllers/platform/properties_test.go
  controllers/platform/scc-crd.yml
  controllers/platform/suite_test.go
  go.mod
  go.sum
  helm/volsync/crds/volsync.backube_replicationdestinations.yaml
  helm/volsync/crds/volsync.backube_replicationsources.yaml
  helm/volsync/templates/clusterrole-manager.yaml
Labels: lgtm, approved, size/XL

#419 Fix typo in comment
  controllers/platform/properties.go
Labels: lgtm, approved, size/XS

#422 Lookup node in affinity getter to set nodeSelector
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/utils/affinity.go
  controllers/utils/affinity_test.go
  helm/volsync/templates/clusterrole-manager.yaml
Labels: lgtm, approved, size/L

#405 detect ipv6 dest addr and pass with [] to rsync
  mover-rsync/source.sh
Labels: lgtm, approved, size/S

#424 rclone: Don't write permission file into data volume
  controllers/mover/rclone/mover.go
  controllers/mover/rclone/rclone_test.go
  mover-rclone/active.sh
Labels: lgtm, approved, size/M

#425 Make 0.4.2 version - remove from stable channel
  bundle.Dockerfile
  bundle/manifests/volsync.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  version.mk
Labels: lgtm, approved, size/S

#430 Update changelog and helm for 0.5.0 release
  CHANGELOG.md
  helm/volsync/Chart.yaml
Labels: lgtm, approved, size/S

#433 update kubectl krew plugin for volsync to 0.5.0
  kubectl-volsync/volsync.yaml
Labels: lgtm, approved, size/XS

#434 Prepare for 0.5.1 - update metadata
  CHANGELOG.md
  bundle/manifests/volsync.clusterserviceversion.yaml
  version.mk
Labels: lgtm, approved, size/S
