Repository backube/volsync, pull requests merged in 2022-02, with the labels that each got.

#111 CLI: Migration create
  kubectl-volsync/cmd/migration.go
  kubectl-volsync/cmd/migration_create.go
  kubectl-volsync/cmd/migration_create_test.go
Labels: lgtm, approved, size/XL

#123 CLI replication create & delete
  Makefile
  go.mod
  kubectl-volsync/cmd/relationship.go
  kubectl-volsync/cmd/relationship_test.go
  kubectl-volsync/cmd/replication.go
  kubectl-volsync/cmd/replication_create.go
  kubectl-volsync/cmd/replication_delete.go
  kubectl-volsync/cmd/replication_test.go
  kubectl-volsync/cmd/suite_test.go
Labels: lgtm, approved, size/XL

#137 Fixing indentation in ReplicationSource example
  docs/usage/restic/database_example.rst
Labels: lgtm, approved, size/S, ok-to-test

#96 CLI: Migration rsync
  kubectl-volsync/cmd/migration.go
  kubectl-volsync/cmd/migration_create.go
  kubectl-volsync/cmd/migration_create_test.go
  kubectl-volsync/cmd/migration_rsync.go
Labels: lgtm, approved, size/L

#139 Use viper to allow both cmd line and env vars for mover container imgs
  controllers/mover/rclone/builder.go
  controllers/mover/rclone/mover.go
  controllers/mover/rclone/rclone_test.go
  controllers/mover/rclone/suite_test.go
  controllers/mover/restic/builder.go
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
  controllers/mover/restic/suite_test.go
  controllers/mover/rsync/builder.go
  controllers/mover/rsync/mover.go
  controllers/mover/rsync/rsync_test.go
  controllers/mover/rsync/suite_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
Labels: lgtm, approved, size/XL

#136 Repo and doc cleanup
  CHANGELOG.md
  README.md
  controllers/mover/restic/suite_test.go
  controllers/volumehandler/suite_test.go
  docs/conf.py
  docs/installation/index.rst
  docs/requirements.txt
  docs/usage/inc_dst_opts.rst
  docs/usage/index.rst
  docs/usage/metrics/index.rst
  docs/usage/rclone/database_example.rst
  docs/usage/rclone/index.rst
  docs/usage/rclone/rclone-secret.rst
  docs/usage/restic/database_example.rst
  docs/usage/restic/index.rst
  docs/usage/rsync/database_example.rst
  docs/usage/rsync/database_example_cross_cluster.rst
  docs/usage/rsync/db_example_cli.rst
  docs/usage/rsync/external_rsync.rst
  docs/usage/rsync/index.rst
  docs/usage/rsync/multi_context_sync_cli.rst
  docs/usage/rsync/plugin_opts.rst
  docs/usage/rsync/ssh_keys.rst
Labels: lgtm, approved, size/XXL

#145 Package olm operator
  .ci-scripts/yamlconfig.yaml
  .gitignore
  Makefile
  Procedures.md
  bundle.Dockerfile
  bundle/manifests/volsync-controller-manager-metrics-service_v1_service.yaml
  bundle/manifests/volsync-manager-config_v1_configmap.yaml
  bundle/manifests/volsync-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/manifests/volsync.backube_replicationdestinations.yaml
  bundle/manifests/volsync.backube_replicationsources.yaml
  bundle/manifests/volsync.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/volsync.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/replicationdestination_controller.go
  controllers/replicationsource_controller.go
Labels: lgtm, approved, size/XXL

#146 Add option to force deployment of mover SCC
  helm/volsync/README.md
  helm/volsync/templates/SCC-mover.yaml
  helm/volsync/values.yaml
Labels: lgtm, approved, size/S
