Repository backube/volsync, pull requests merged in 2022-07, with the labels that each got.

#298 Update bundle files from syncthing merge
  bundle/manifests/volsync.backube_replicationsources.yaml
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/manager/kustomization.yaml
Labels: lgtm, approved, size/M

#292 Enable Pod Security Admission in kind
  hack/setup-kind-cluster.sh
Labels: lgtm, approved, size/M

#303 Add RWO volume affinity to Syncthing
  controllers/mover/syncthing/mover.go
  controllers/utils/affinity.go
  controllers/utils/affinity_test.go
  test-kuttl/e2e/syncthing-cluster-sync/10-connect-syncthings.yaml
  test-kuttl/e2e/syncthing-cluster-sync/15-verify-all-connected.yaml
  test-kuttl/e2e/syncthing-cluster-sync/20-populate-syncthing-1-data.yaml
  test-kuttl/e2e/syncthing-cluster-sync/25-verify-data-synced.yaml
  test-kuttl/e2e/syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect.yaml
  test-kuttl/e2e/syncthing-cluster-sync/35-verify-all-are-connected.yaml
Labels: lgtm, approved, size/M

#304 automate injecting skiprange/replaces in csv
  Makefile
  Procedures.md
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/manifests/bases/volsync.clusterserviceversion.yaml
  version.mk
Labels: lgtm, approved, size/M

#288 Automatically close inactive PRs
  .github/workflows/stale.yml
Labels: lgtm, approved, size/M

#296 Update kube-rbac-proxy to v0.13.0
  CHANGELOG.md
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  helm/volsync/Chart.yaml
  helm/volsync/templates/deployment-controller.yaml
Labels: lgtm, approved, size/S

#302 Delete/recreate jobs if immutable field needs update
  controllers/mover/rclone/mover.go
  controllers/mover/rclone/rclone_test.go
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
  controllers/mover/rsync/mover.go
  controllers/mover/rsync/rsync_test.go
  controllers/utils/reconcile.go
  controllers/utils/reconcile_test.go
Labels: lgtm, approved, size/L

#308 Add Syncthing to the Helm chart
  .github/workflows/operator.yml
  helm/volsync/Chart.yaml
  helm/volsync/templates/deployment-controller.yaml
  helm/volsync/values.yaml
Labels: lgtm, approved, size/S

#315 CI: Fix env substitution when calling push workflow
  .github/workflows/operator.yml
Labels: lgtm, approved, size/S

#318 Backport GH actions changes to enable periodic builds
  .github/workflows/documentation.yml
  .github/workflows/operator.yml
  .github/workflows/registry-push.yml
Labels: lgtm, approved, size/L

#322 Enable periodic builds of release-0.4
  .github/workflows/periodic.yml
Labels: lgtm, approved, size/XS

#316 Unit test flakes client cache
  controllers/mover/rclone/rclone_test.go
  controllers/mover/rclone/suite_test.go
  controllers/mover/restic/restic_test.go
  controllers/mover/restic/suite_test.go
  controllers/mover/rsync/rsync_test.go
  controllers/mover/rsync/suite_test.go
  controllers/mover/syncthing/suite_test.go
  controllers/mover/syncthing/syncthing_test.go
  controllers/rclone_mover_test.go
  controllers/replicationdestination_test.go
  controllers/replicationsource_test.go
  controllers/suite_test.go
  controllers/utils/cleanup_test.go
  controllers/utils/utils_suite_test.go
  controllers/volumehandler/suite_test.go
  controllers/volumehandler/volumehandler.go
  controllers/volumehandler/volumehandler_test.go
Labels: lgtm, approved, size/XXL

#314 Syncthing: Fix CI e2e
  hack/run-in-kind.sh
  mover-syncthing/Dockerfile
  mover-syncthing/config.xml
  mover-syncthing/entry.sh
  test-kuttl/e2e/syncthing-cluster-sync/20-assert.yaml
  test-kuttl/e2e/syncthing-cluster-sync/20-populate-syncthing-1-data.yaml
  test-kuttl/e2e/syncthing-cluster-sync/25-assert.yaml
  test-kuttl/e2e/syncthing-cluster-sync/25-verify-data-synced.yaml
  test-kuttl/e2e/syncthing-cluster-sync/30-kill-syncthing-pods-and-reconnect.yaml
Labels: lgtm, approved, size/M

#328 Update hostpath driver to v1.9 & enable fsGroup
  hack/setup-kind-cluster.sh
Labels: lgtm, approved, size/M

#329 Update rclone to v1.59.0
  CHANGELOG.md
  helm/volsync/Chart.yaml
  mover-rclone/Dockerfile
Labels: lgtm, approved, size/XS

#330 ci: Enable periodic builds of release-0.5
  .github/workflows/periodic.yml
Labels: lgtm, approved, size/XS

#331 Update VolSync description in csv
  Procedures.md
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/manifests/bases/volsync.clusterserviceversion.yaml
Labels: lgtm, approved, size/M

#333 Fix typo in readme/csv description
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/manifests/bases/volsync.clusterserviceversion.yaml
  helm/volsync/README.md
Labels: lgtm, approved, size/XS

#337 Doc update suggestions from Christopher Dawson
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/manifests/bases/volsync.clusterserviceversion.yaml
  helm/volsync/README.md
Labels: lgtm, approved, size/L
