Repository backube/volsync, pull requests merged in 2023-10, with the labels that each got.

#914 Renovate: Group syncthing updates into single PR
  renovate.json5
Labels: lgtm, approved, size/S

#915 Update the versions of kube we test on
  .github/workflows/operator.yml
  hack/setup-kind-cluster.sh
Labels: lgtm, approved, size/S

#923 Uppdate k8s.io/utils digest to 3b25d92
  controllers/mover/rclone/mover.go
  controllers/mover/rclone/rclone_test.go
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
  controllers/mover/rsync/mover.go
  controllers/mover/rsync/rsync_test.go
  controllers/mover/rsynctls/mover.go
  controllers/mover/rsynctls/rsync_test.go
  controllers/mover/syncthing/mover.go
  controllers/mover/syncthing/syncthing_test.go
  controllers/utils/cleanup_test.go
  go.mod
  go.sum
  kubectl-volsync/cmd/replication_test.go
Labels: lgtm, approved, size/L

#924 Disable automatic updates of openshift/api
  go.mod
  go.sum
  renovate.json5
Labels: lgtm, approved, size/S

#925 CHANGELOG update syncthing v1.25.0
  CHANGELOG.md
  Dockerfile
Labels: lgtm, approved, size/XS

#936 Update custom-scorecard-tests img tag release-0.8
  custom-scorecard-tests/config.yaml
  custom-scorecard-tests/scorecard/patches/deploy-prereqs.yaml
  custom-scorecard-tests/scorecard/patches/e2e-tests.yaml
Labels: lgtm, approved, size/L

#937 Enable periodic builds of release-0.8
  .github/workflows/periodic.yml
Labels: lgtm, approved, size/XS

#960 Enable TCP-level keepalive for rsync-tls mover
  mover-rsync-tls/client.sh
  mover-rsync-tls/server.sh
Labels: lgtm, approved, size/S

#966 Restic v0.16.2
  CHANGELOG.md
  mover-restic/SOURCE_VERSIONS
  mover-restic/restic/.readthedocs.yaml
  mover-restic/restic/CHANGELOG.md
  mover-restic/restic/VERSION
  mover-restic/restic/changelog/0.14.0_2022-08-25/pull-3475
  mover-restic/restic/changelog/0.16.2_2023-10-29/issue-4540
  mover-restic/restic/changelog/0.16.2_2023-10-29/pull-4545
  mover-restic/restic/cmd/restic/global.go
  mover-restic/restic/doc/030_preparing_a_new_repo.rst
  mover-restic/restic/doc/040_backup.rst
  mover-restic/restic/doc/045_working_with_repos.rst
  mover-restic/restic/doc/050_restore.rst
  mover-restic/restic/doc/conf.py
  mover-restic/restic/helpers/build-release-binaries/main.go
  mover-restic/restic/helpers/verify-release-binaries.sh
  mover-restic/restic/internal/fuse/file.go
  mover-restic/restic/internal/repository/repository.go
  mover-restic/restic/internal/restic/repository.go
Labels: lgtm, approved, size/L
