Repository backube/volsync, pull requests merged in 2023-09, with the labels that each got.

#849 Generate server certs at startup if first time
  Dockerfile
  mover-syncthing/entry.sh
Labels: lgtm, approved, size/S

#854 Update Syncthing to v1.24.0
  CHANGELOG.md
  Dockerfile
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#859 Update operator sdk v1.31.0
  Dockerfile.volsync-custom-scorecard-tests
  Makefile
  bundle.Dockerfile
  bundle/manifests/volsync.backube_replicationdestinations.yaml
  bundle/manifests/volsync.backube_replicationsources.yaml
  bundle/manifests/volsync.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/crd/bases/volsync.backube_replicationdestinations.yaml
  config/crd/bases/volsync.backube_replicationsources.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  helm/volsync/templates/volsync.backube_replicationdestinations.yaml
  helm/volsync/templates/volsync.backube_replicationsources.yaml
Labels: lgtm, approved, size/M

#861 Update rclone to v1.64.0
  CHANGELOG.md
  Dockerfile
Labels: lgtm, approved, size/XS

#864 unit test- timing update
  controllers/volumepopulator_controller_test.go
Labels: lgtm, approved, size/M

#862 Update controller-runtime to v0.16.2
  controllers/mover/rclone/suite_test.go
  controllers/mover/restic/suite_test.go
  controllers/mover/rsync/suite_test.go
  controllers/mover/rsynctls/suite_test.go
  controllers/mover/syncthing/suite_test.go
  controllers/suite_test.go
  controllers/volumehandler/suite_test.go
  go.mod
  go.sum
  main.go
Labels: lgtm, approved, size/M

#871 Switch to pre-commit for linting
  .ci-scripts/pre-commit.sh
  .ci-scripts/yamlconfig.yaml
  .github/workflows/operator.yml
  .pre-commit-config.yaml
  controllers/mover/rclone/logfilter_test.go
  controllers/mover/rsynctls/logfilter_test.go
  docs/design/mover-rsync.rst
  docs/design/rwo-affinity.rst
  docs/usage/cli/migration.rst
  docs/usage/index.rst
  docs/usage/rclone/database_example.rst
  docs/usage/rclone/index.rst
  docs/usage/restic/database_example.rst
  docs/usage/restic/index.rst
  docs/usage/rsync/database_example.rst
  docs/usage/rsync/external_rsync.rst
  docs/usage/rsync/ssh_keys.rst
  docs/usage/syncthing/index.rst
  docs/usage/syncthing/syncthing_example.rst
  docs/usage/triggers.rst
  examples/rclone/rclone.conf
  hack/crds/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  mover-rclone/rclone.conf
  mover-syncthing/config-template.xml
  mover-syncthing/stignore-template
  test-e2e/ansible.cfg
Labels: lgtm, approved, size/L

#881 golangci-lint to v1.54.2 and linting fixes
  Makefile
  api/v1alpha1/events.go
  controllers/mover/rclone/rclone_test.go
  controllers/mover/restic/restic_test.go
  controllers/mover/rsync/builder.go
  controllers/mover/rsync/rsync_test.go
  controllers/mover/rsynctls/rsync_test.go
  controllers/mover/syncthing/api/api_test.go
  controllers/mover/syncthing/api/utils.go
  controllers/mover/syncthing/builder.go
  controllers/mover/syncthing/mover.go
  controllers/mover/syncthing/syncthing.go
  controllers/statemachine/fake_machine.go
  controllers/statemachine/machine.go
  controllers/utils/sahandler.go
  controllers/volumehandler/volumehandler_test.go
  controllers/volumepopulator_controller_test.go
  kubectl-volsync/cmd/parse_test.go
  kubectl-volsync/cmd/replication_delete.go
  kubectl-volsync/cmd/replication_sync.go
Labels: lgtm, approved, size/L

#875 git clone and run go build for diskrsync
  Dockerfile
  diskrsync-tcp/main.go
  renovate.json5
Labels: lgtm, approved, size/M

#887 Collapse the 2 require sections in go.mod
  go.mod
Labels: lgtm, approved, size/XS

#895 Update custom-scorecard-tests img to python v3.11
  Dockerfile.volsync-custom-scorecard-tests
Labels: lgtm, approved, size/S

#896 Enable auto-update of yq
  Makefile
  renovate.json5
Labels: lgtm, approved, size/S

#898 test-e2e-install target, make --user flag optional
  Makefile
Labels: lgtm, approved, size/XS

#901 Revert "Update rclone to v1.64.0"
  CHANGELOG.md
  Dockerfile
Labels: lgtm, approved, size/XS

#897 e2e tests - remove importlib-resources dependency
  test-e2e/Pipfile
  test-e2e/Pipfile.lock
Labels: lgtm, approved, size/S
