Repository backube/volsync, pull requests merged in 2023-08, with the labels that each got.

#816 Version 0.7.4
  bundle/manifests/volsync.clusterserviceversion.yaml
  version.mk
Labels: lgtm, approved, size/S

#821 Update client-go to 0.26.7
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#824 Use YQ v4.34.2 because latest (v4.35.1) requires golang 1.20
  Makefile
Labels: lgtm, approved, size/XS

#825 Update rclone to v1.63.1
  CHANGELOG.md
  Dockerfile
Labels: lgtm, approved, size/XS

#826 Update syncthing to v1.23.7
  CHANGELOG.md
  Dockerfile
  go.mod
  go.sum
Labels: lgtm, approved, size/L

#835 Update to build with go1.20
  .github/workflows/operator.yml
  Dockerfile
  Makefile
  custom-scorecard-tests/go.mod
  go.mod
Labels: lgtm, approved, size/S

#836 Update release-0.7 to build with go1.20
  .github/workflows/operator.yml
  Dockerfile
  Makefile
  custom-scorecard-tests/go.mod
  go.mod
Labels: lgtm, approved, size/S

#837 Update release-0.6 to build with go1.20
  .github/workflows/operator.yml
  Dockerfile
  Makefile
  custom-scorecard-tests/go.mod
  go.mod
  go.sum
  mover-rclone/Dockerfile
  mover-restic/Dockerfile
Labels: lgtm, approved, size/L

#841 version v0.5.5
  bundle/manifests/volsync.clusterserviceversion.yaml
  version.mk
Labels: lgtm, approved, size/S

#840 version v0.6.4
  bundle/manifests/volsync.clusterserviceversion.yaml
  version.mk
Labels: lgtm, approved, size/S

#833 Volume populator docs
  CHANGELOG.md
  docs/usage/index.rst
  docs/usage/rclone/database_example.rst
  docs/usage/restic/database_example.rst
  docs/usage/rsync/database_example.rst
  docs/usage/volume-populator/index.rst
  examples/destination-database/mysql-pvc.yaml
  examples/rclone/rclone.conf
  examples/rclone/volsync_v1alpha1_replicationdestination.yaml
  examples/rclone/volsync_v1alpha1_replicationsource.yaml
Labels: lgtm, approved, size/L

#846 bump kube apis to v0.28.1
  bundle/manifests/volsync.backube_replicationdestinations.yaml
  bundle/manifests/volsync.backube_replicationsources.yaml
  config/crd/bases/volsync.backube_replicationdestinations.yaml
  config/crd/bases/volsync.backube_replicationsources.yaml
  go.mod
  go.sum
  helm/volsync/templates/volsync.backube_replicationdestinations.yaml
  helm/volsync/templates/volsync.backube_replicationsources.yaml
Labels: lgtm, approved, size/L

#848 Fix cronspec validation
  api/v1alpha1/replicationdestination_types.go
  api/v1alpha1/replicationsource_types.go
  bundle/manifests/volsync.backube_replicationdestinations.yaml
  bundle/manifests/volsync.backube_replicationsources.yaml
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/crd/bases/volsync.backube_replicationdestinations.yaml
  config/crd/bases/volsync.backube_replicationsources.yaml
  controllers/statemachine/machine_test.go
  helm/volsync/templates/volsync.backube_replicationdestinations.yaml
  helm/volsync/templates/volsync.backube_replicationsources.yaml
  mover-restic/entry.sh
  mover-rsync-tls/client.sh
Labels: lgtm, approved, size/M
