Repository backube/volsync, pull requests merged in 2023-02, with the labels that each got.

#614 Remove 0.5.2 from stable channel
  bundle.Dockerfile
  bundle/metadata/annotations.yaml
  version.mk
Labels: lgtm, approved, size/XS

#612 Include cluster wide proxy env vars on restic mover
  controllers/mover/rclone/mover.go
  controllers/mover/rclone/rclone_test.go
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
  controllers/mover/syncthing/mover.go
  controllers/mover/syncthing/syncthing_test.go
  controllers/utils/utils.go
Labels: lgtm, approved, size/L, ok-to-test

#621 Revert "Remove replaces 0.5.1 from csv"
  bundle/manifests/volsync.clusterserviceversion.yaml
  version.mk
Labels: lgtm, approved, size/XS

#634 GOFLAGS= to remove -mod=readonly when getting yq
  Makefile
Labels: lgtm, approved, size/XS

#624 changelog and helm updates for 0.6.0
  CHANGELOG.md
  helm/volsync/Chart.yaml
Labels: lgtm, approved, size/M

#638 Merge pull request #634 from tesshuflower/make_yq_fix
  Makefile
Labels: lgtm, approved, size/XS

#639 Merge pull request #634 from tesshuflower/make_yq_fix
  Makefile
Labels: lgtm, approved, size/XS

#640 Merge pull request #624 from tesshuflower/update_changelog_for_0.6.0
  CHANGELOG.md
  helm/volsync/Chart.yaml
Labels: lgtm, approved, size/M

#641 Update changelog for prev 0.5.2 and also update changelog for upcoming 0.6.1 release
  CHANGELOG.md
Labels: lgtm, approved, size/S

#645 add moverServiceAccount to spec for advanced usage
  CHANGELOG.md
  api/v1alpha1/replicationdestination_types.go
  api/v1alpha1/replicationsource_types.go
  api/v1alpha1/rsync_tls_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/volsync.backube_replicationdestinations.yaml
  bundle/manifests/volsync.backube_replicationsources.yaml
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/crd/bases/volsync.backube_replicationdestinations.yaml
  config/crd/bases/volsync.backube_replicationsources.yaml
  controllers/mover/rclone/builder.go
  controllers/mover/rclone/mover.go
  controllers/mover/rclone/rclone_test.go
  controllers/mover/restic/builder.go
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
  controllers/mover/rsync/builder.go
  controllers/mover/rsync/mover.go
  controllers/mover/rsync/rsync_test.go
  controllers/mover/rsynctls/builder.go
  controllers/mover/rsynctls/mover.go
  controllers/mover/rsynctls/rsync_test.go
  controllers/mover/syncthing/builder.go
  controllers/mover/syncthing/mover.go
  controllers/mover/syncthing/syncthing_test.go
  controllers/utils/sahandler.go
  helm/volsync/templates/volsync.backube_replicationdestinations.yaml
  helm/volsync/templates/volsync.backube_replicationsources.yaml
Labels: lgtm, approved, size/XXL

#649 Versioning for v0.6.1
  bundle/manifests/volsync.clusterserviceversion.yaml
  helm/volsync/Chart.yaml
  version.mk
Labels: lgtm, approved, size/S

#650 versioning for v0.7.0
  bundle.Dockerfile
  bundle/manifests/volsync.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  helm/volsync/Chart.yaml
  version.mk
Labels: lgtm, approved, size/S

#651 Merge pull request #612 from dymurray/proxy
  controllers/mover/rclone/mover.go
  controllers/mover/rclone/rclone_test.go
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
  controllers/mover/syncthing/mover.go
  controllers/mover/syncthing/syncthing_test.go
  controllers/utils/utils.go
Labels: lgtm, approved, size/L
