Repository backube/volsync, pull requests merged in 2023-05, with the labels that each got.

#739 Update readthedocs config to use python 3.11
  .readthedocs.yml
Labels: lgtm, approved, size/XS

#742 Version v0.7.2
  bundle/manifests/volsync.clusterserviceversion.yaml
  helm/volsync/Chart.yaml
  version.mk
Labels: lgtm, approved, size/S

#738 Restrict rbac proxy to tls1.3 minimum
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  helm/volsync/templates/deployment-controller.yaml
Labels: lgtm, approved, size/XS

#743 Merge pull request #738 from tesshuflower/rbac-proxy-tls1.3
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/default/manager_auth_proxy_patch.yaml
  helm/volsync/templates/deployment-controller.yaml
Labels: lgtm, approved, size/XS

#745 `go get github.com/openshift/api@release-4.13 && go mod tidy`
  go.mod
  go.sum
Labels: lgtm, approved, size/XS, ok-to-test

#751 Restic rclone env vars
  CHANGELOG.md
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
Labels: lgtm, approved, size/M
