Repository backube/volsync, pull requests merged in 2023-01, with the labels that each got.

#579 tests: Update kind cluster to use external-snapshotter v6.2.1
  hack/setup-kind-cluster.sh
Labels: lgtm, approved, size/XS

#583 e2e: Make NS delete more robust
  test-e2e/roles/create_namespace/handlers/main.yml
Labels: lgtm, approved, size/XS

#591 rsync-tls: Give time for rsync to complete
  mover-rsync-tls/client.sh
  mover-rsync-tls/server.sh
Labels: lgtm, approved, size/XS

#590 ci: Update the version of csi hostpath driver
  hack/setup-kind-cluster.sh
Labels: lgtm, approved, size/S

#588 Remove extra build files
  .dockerignore
  mover-rclone/Dockerfile
  mover-rclone/Makefile
  mover-rclone/README.md
  mover-rclone/deploydestination.yaml
  mover-rclone/deploysource.yaml
  mover-restic/Dockerfile
  mover-restic/Makefile
  mover-restic/example.yaml
  mover-rsync-tls/Dockerfile
  mover-rsync-tls/Makefile
  mover-rsync/Dockerfile
  mover-rsync/Makefile
  mover-rsync/README.md
  mover-rsync/deploy-destination.yaml
  mover-rsync/deploy-source.yaml
  mover-rsync/make-keys.sh
  mover-syncthing/Dockerfile
  mover-syncthing/Makefile
Labels: lgtm, approved, size/XL

#595 Golang1.19 for release 0.5
  .github/workflows/operator.yml
  Dockerfile
  Makefile
  api/v1alpha1/common_types.go
  api/v1alpha1/groupversion_info.go
  api/v1alpha1/replicationdestination_types.go
  api/v1alpha1/replicationsource_types.go
  controllers/mover/restic/suite_test.go
  controllers/mover/rsync/mover.go
  controllers/mover/rsync/rsync_common.go
  controllers/mover/syncthing/api/connection_utils.go
  controllers/mover/syncthing/mover.go
  controllers/suite_test.go
  controllers/utils/affinity.go
  controllers/volumehandler/volumehandler.go
  go.mod
  go.sum
  kubectl-volsync/cmd/migration_create_test.go
  kubectl-volsync/cmd/migration_delete_test.go
  kubectl-volsync/cmd/migration_rsync.go
  kubectl-volsync/cmd/relationship_test.go
  kubectl-volsync/cmd/replication_test.go
  mover-rclone/Dockerfile
  mover-restic/Dockerfile
Labels: lgtm, approved, size/L

#593 Return status info from movers
  api/v1alpha1/common_types.go
  api/v1alpha1/replicationdestination_types.go
  api/v1alpha1/replicationsource_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/volsync.backube_replicationdestinations.yaml
  bundle/manifests/volsync.backube_replicationsources.yaml
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/crd/bases/volsync.backube_replicationdestinations.yaml
  config/crd/bases/volsync.backube_replicationsources.yaml
  config/rbac/role.yaml
  controllers/mover/rclone/builder.go
  controllers/mover/rclone/logfilter.go
  controllers/mover/rclone/logfilter_test.go
  controllers/mover/rclone/mover.go
  controllers/mover/rclone/suite_test.go
  controllers/mover/restic/builder.go
  controllers/mover/restic/logfilter.go
  controllers/mover/restic/logfilter_test.go
  controllers/mover/restic/mover.go
  controllers/mover/restic/suite_test.go
  controllers/mover/rsync/builder.go
  controllers/mover/rsync/logfilter.go
  controllers/mover/rsync/logfilter_test.go
  controllers/mover/rsync/mover.go
  controllers/mover/rsync/suite_test.go
  controllers/mover/rsynctls/builder.go
  controllers/mover/rsynctls/logfilter.go
  controllers/mover/rsynctls/logfilter_test.go
  controllers/mover/rsynctls/mover.go
  controllers/mover/rsynctls/suite_test.go
  controllers/suite_test.go
  controllers/utils/podlogs.go
  controllers/utils/podlogs_test.go
  controllers/utils/utils_suite_test.go
  go.mod
  go.sum
  helm/volsync/templates/clusterrole-manager.yaml
  helm/volsync/templates/volsync.backube_replicationdestinations.yaml
  helm/volsync/templates/volsync.backube_replicationsources.yaml
  main.go
  mover-rclone/active.sh
  test-e2e/test_rclone_normal.yml
  test-e2e/test_rclone_priv.yml
  test-e2e/test_restic_manual_normal.yml
  test-e2e/test_restic_manual_priv.yml
  test-e2e/test_rsync_tls_normal.yml
  test-e2e/test_rsync_tls_priv.yml
  test-e2e/test_simple_rsync.yml
Labels: lgtm, approved, size/XXL

#598 Remove replaces 0.5.1 from csv
  bundle/manifests/volsync.clusterserviceversion.yaml
  version.mk
Labels: lgtm, approved, size/XS

#600 Annotate gh action versions w/ their tag
  .github/workflows/documentation.yml
  .github/workflows/operator.yml
  .github/workflows/periodic.yml
  .github/workflows/registry-push.yml
  .github/workflows/stale.yml
Labels: lgtm, approved, size/M

#606 e2e: Try to make syncthing pod killing more robust
  test-e2e/roles/test_syncthing_cluster_sync/tasks/kill_pods_by_label.yml
  test-e2e/roles/test_syncthing_cluster_sync/tasks/main.yml
Labels: lgtm, approved, size/S

#605 Update syncthing to v1.23.0 (from v1.22.2)
  Dockerfile
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#604 rsync-tls: add logfilter for failed mover job
  controllers/mover/rsynctls/logfilter.go
  controllers/mover/rsynctls/logfilter_test.go
  controllers/mover/rsynctls/mover.go
  controllers/utils/podlogs.go
  controllers/utils/podlogs_test.go
Labels: lgtm, approved, size/XL

#607 svc annotations in spec (rsync & rsync-tls)
  api/v1alpha1/replicationdestination_types.go
  api/v1alpha1/rsync_tls_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/volsync.backube_replicationdestinations.yaml
  config/crd/bases/volsync.backube_replicationdestinations.yaml
  controllers/mover/rsync/builder.go
  controllers/mover/rsync/mover.go
  controllers/mover/rsync/rsync_common.go
  controllers/mover/rsync/rsync_test.go
  controllers/mover/rsynctls/builder.go
  controllers/mover/rsynctls/mover.go
  controllers/mover/rsynctls/rsync_common.go
  controllers/mover/rsynctls/rsync_test.go
  helm/volsync/templates/volsync.backube_replicationdestinations.yaml
Labels: lgtm, approved, size/L
