Repository backube/volsync, pull requests merged in 2024-07, with the labels that each got.

#1324 Update restic to v0.16.5
  mover-restic/SOURCE_VERSIONS
  mover-restic/restic/CHANGELOG.md
  mover-restic/restic/VERSION
  mover-restic/restic/changelog/0.16.5_2024-07-01/issue-4873
  mover-restic/restic/changelog/0.16.5_2024-07-01/pull-4799
  mover-restic/restic/cmd/restic/global.go
  mover-restic/restic/doc/030_preparing_a_new_repo.rst
  mover-restic/restic/doc/040_backup.rst
  mover-restic/restic/go.mod
  mover-restic/restic/go.sum
  mover-restic/restic/helpers/verify-release-binaries.sh
  mover-restic/restic/internal/backend/azure/azure.go
  mover-restic/restic/internal/backend/azure/config.go
Labels: lgtm, approved, size/XXL

#1331 more logging in server side rsync-tls script
  mover-rsync-tls/server.sh
Labels: lgtm, approved, size/XS

#1337 update external-snapshotter to v8
  controllers/mover/rclone/mover.go
  controllers/mover/rclone/rclone_test.go
  controllers/mover/rclone/suite_test.go
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
  controllers/mover/restic/suite_test.go
  controllers/mover/rsync/mover.go
  controllers/mover/rsync/rsync_test.go
  controllers/mover/rsync/suite_test.go
  controllers/mover/rsynctls/mover.go
  controllers/mover/rsynctls/rsync_test.go
  controllers/mover/rsynctls/suite_test.go
  controllers/mover/syncthing/suite_test.go
  controllers/platform/suite_test.go
  controllers/rclone_mover_test.go
  controllers/replicationdestination_controller.go
  controllers/replicationdestination_test.go
  controllers/replicationsource_controller.go
  controllers/replicationsource_test.go
  controllers/suite_test.go
  controllers/utils/cleanup.go
  controllers/utils/cleanup_test.go
  controllers/utils/utils_suite_test.go
  controllers/volumehandler/suite_test.go
  controllers/volumehandler/volumehandler.go
  controllers/volumehandler/volumehandler_test.go
  controllers/volumepopulator_controller.go
  controllers/volumepopulator_controller_test.go
  go.mod
  go.sum
  kubectl-volsync/cmd/suite_test.go
  main.go
Labels: lgtm, approved, size/M

#1340 feat: Add MoverAffinity field to MoverConfig
  api/v1alpha1/common_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/volsync.backube_replicationdestinations.yaml
  bundle/manifests/volsync.backube_replicationsources.yaml
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/crd/bases/volsync.backube_replicationdestinations.yaml
  config/crd/bases/volsync.backube_replicationsources.yaml
  controllers/utils/utils.go
  controllers/utils/utils_test.go
  helm/volsync/templates/volsync.backube_replicationdestinations.yaml
  helm/volsync/templates/volsync.backube_replicationsources.yaml
Labels: lgtm, approved, ok-to-test, size/XXL

#1346 update changelog, charts etc for v0.10.0 release
  CHANGELOG.md
  helm/volsync/Chart.yaml
  kubectl-volsync/volsync.yaml
Labels: lgtm, approved, size/M
