Repository backube/volsync, pull requests merged in 2024-12, with the labels that each got.

#1478 Rsync e2e usepam no
  Dockerfile
Labels: lgtm, approved, size/S

#1466 Sync only the target filesystem at the end of mover tasks
  mover-rclone/active.sh
  mover-restic/entry.sh
  mover-rsync-tls/server.sh
  mover-rsync/destination.sh
  mover-rsync/source.sh
Labels: lgtm, approved, size/S, ok-to-test

#1486 update version to v0.12.0 and charts version too for next release
  bundle.Dockerfile
  bundle/manifests/volsync.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  helm/volsync/Chart.yaml
  version.mk
Labels: lgtm, approved, size/S

#1490 helm update - put kube-rbac-proxy img in values
  helm/volsync/templates/deployment-controller.yaml
  helm/volsync/values.yaml
Labels: lgtm, approved, size/XS

#1493 Bump golang.org/x/crypto to 0.31.0
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#1494 [Release-0.10] version for volsyncv0.10.2
  bundle.Dockerfile
  bundle/manifests/volsync.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  go.mod
  go.sum
  version.mk
Labels: lgtm, approved, size/L

#1495 [Release-0.11] version for volsync v0.11.1
  .github/workflows/operator.yml
  bundle/manifests/volsync.clusterserviceversion.yaml
  go.mod
  go.sum
  helm/volsync/Chart.yaml
  version.mk
Labels: lgtm, approved, size/L

#1499 Update custom-scorecard-tests for release-0.12 and set version in charts.yml for upcoming pre-release rc.1
  custom-scorecard-tests/config-downstream.yaml
  custom-scorecard-tests/config.yaml
  custom-scorecard-tests/scorecard/bases/patches/deploy-prereqs-stage0.yaml
  custom-scorecard-tests/scorecard/bases/patches/e2e-tests-stage1.yaml
  custom-scorecard-tests/scorecard/bases/patches/e2e-tests-stage2.yaml
  helm/volsync/Chart.yaml
Labels: lgtm, approved, size/L
