Repository backube/volsync, pull requests merged in 2024-02, with the labels that each got.

#1079 Pass through additional restic env vars
  controllers/mover/restic/mover.go
Labels: lgtm, approved, size/S

#1081 version for upcoming v0.9.0 release
  bundle.Dockerfile
  bundle/manifests/volsync.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  version.mk
Labels: lgtm, approved

#1080 Copy trigger annotations
  api/v1alpha1/common_types.go
  api/v1alpha1/events.go
  controllers/errors/errors.go
  controllers/errors/errors_suite_test.go
  controllers/errors/errors_test.go
  controllers/mover/rclone/mover.go
  controllers/mover/rclone/rclone_test.go
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
  controllers/mover/rsync/mover.go
  controllers/mover/rsynctls/mover.go
  controllers/mover/rsynctls/rsync_test.go
  controllers/replicationsource_controller.go
  controllers/utils/copy_trigger_annotations.go
  controllers/utils/podlogs.go
  controllers/volumehandler/volumehandler.go
  custom-scorecard-tests/config.yaml
  custom-scorecard-tests/scorecard/kustomization.yaml
  custom-scorecard-tests/scorecard/patches/e2e-tests.yaml
  main.go
  test-e2e/test_restic_manual_normal_copy_trigger.yml
Labels: lgtm, approved, size/XXL

#1084 Update restic to v0.16.4
  CHANGELOG.md
  mover-restic/SOURCE_VERSIONS
  mover-restic/restic/CHANGELOG.md
  mover-restic/restic/VERSION
  mover-restic/restic/changelog/0.16.4_2024-02-04/issue-4529
  mover-restic/restic/changelog/0.16.4_2024-02-04/issue-4677
  mover-restic/restic/cmd/restic/global.go
  mover-restic/restic/doc/047_tuning_backup_parameters.rst
  mover-restic/restic/doc/bash-completion.sh
  mover-restic/restic/doc/man/restic-backup.1
  mover-restic/restic/doc/man/restic-cache.1
  mover-restic/restic/doc/man/restic-cat.1
  mover-restic/restic/doc/man/restic-check.1
  mover-restic/restic/doc/man/restic-copy.1
  mover-restic/restic/doc/man/restic-diff.1
  mover-restic/restic/doc/man/restic-dump.1
  mover-restic/restic/doc/man/restic-find.1
  mover-restic/restic/doc/man/restic-forget.1
  mover-restic/restic/doc/man/restic-generate.1
  mover-restic/restic/doc/man/restic-init.1
  mover-restic/restic/doc/man/restic-key.1
  mover-restic/restic/doc/man/restic-list.1
  mover-restic/restic/doc/man/restic-ls.1
  mover-restic/restic/doc/man/restic-migrate.1
  mover-restic/restic/doc/man/restic-mount.1
  mover-restic/restic/doc/man/restic-prune.1
  mover-restic/restic/doc/man/restic-recover.1
  mover-restic/restic/doc/man/restic-repair-index.1
  mover-restic/restic/doc/man/restic-repair-packs.1
  mover-restic/restic/doc/man/restic-repair-snapshots.1
  mover-restic/restic/doc/man/restic-repair.1
  mover-restic/restic/doc/man/restic-restore.1
  mover-restic/restic/doc/man/restic-rewrite.1
  mover-restic/restic/doc/man/restic-self-update.1
  mover-restic/restic/doc/man/restic-snapshots.1
  mover-restic/restic/doc/man/restic-stats.1
  mover-restic/restic/doc/man/restic-tag.1
  mover-restic/restic/doc/man/restic-unlock.1
  mover-restic/restic/doc/man/restic-version.1
  mover-restic/restic/doc/man/restic.1
  mover-restic/restic/go.mod
  mover-restic/restic/go.sum
  mover-restic/restic/internal/archiver/archiver_test.go
  mover-restic/restic/internal/migrations/upgrade_repo_v2_test.go
  mover-restic/restic/internal/pack/pack.go
  mover-restic/restic/internal/pack/pack_internal_test.go
  mover-restic/restic/internal/repository/fuzz_test.go
  mover-restic/restic/internal/repository/repack_test.go
  mover-restic/restic/internal/repository/repository.go
  mover-restic/restic/internal/repository/repository_internal_test.go
  mover-restic/restic/internal/repository/testing.go
  mover-restic/restic/internal/restic/lock_test.go
Labels: lgtm, approved, size/XL

#1046 PRs that have "hold" label should not be marked stale
  .github/workflows/stale.yml
Labels: lgtm, approved, size/XS

#1087 update mem limit in olm deployments of volsync
  bundle/manifests/volsync.clusterserviceversion.yaml
  config/manager/manager.yaml
  helm/volsync/values.yaml
Labels: lgtm, approved, size/XS

#1090 cust-scorecard-tests - reduce parallelism
  custom-scorecard-tests/config.yaml
  custom-scorecard-tests/generateE2ETestsConfig.sh
  custom-scorecard-tests/scorecard/bases/config.yaml
  custom-scorecard-tests/scorecard/kustomization.yaml
  custom-scorecard-tests/scorecard/patches/deploy-prereqs-stage0.yaml
  custom-scorecard-tests/scorecard/patches/e2e-tests-stage1.yaml
  custom-scorecard-tests/scorecard/patches/e2e-tests-stage2.yaml
  hack/ensure-volsync-test-runner.sh
Labels: lgtm, approved, size/L

#1092 Update custom-scorecard-tests img tag release-0.9
  custom-scorecard-tests/config.yaml
  custom-scorecard-tests/scorecard/patches/deploy-prereqs-stage0.yaml
  custom-scorecard-tests/scorecard/patches/e2e-tests-stage1.yaml
  custom-scorecard-tests/scorecard/patches/e2e-tests-stage2.yaml
Labels: lgtm, approved, size/L

#1093 Enable periodic builds of release-0.9
  .github/workflows/periodic.yml
Labels: lgtm, approved, size/XS

#1101 Rclone env vars
  controllers/mover/rclone/mover.go
  controllers/mover/rclone/rclone_test.go
  controllers/mover/restic/mover.go
  controllers/utils/utils.go
  controllers/utils/utils_test.go
  docs/usage/rclone/rclone-secret.rst
Labels: lgtm, approved, size/L

#1103 docs for mover resource requests/limits
  docs/usage/index.rst
  docs/usage/resourcerequirements.rst
Labels: lgtm, approved, size/M

#984 ci: Limit the amount of parallelism in e2e tests
  .github/workflows/operator.yml
  api/v1alpha1/events.go
  controllers/mover/syncthing/mover.go
Labels: lgtm, approved, size/S

#1108 Increase number of PRs renovate can have open
  renovate.json5
Labels: lgtm, approved, size/XS

#1104 Add ipv6 checker in mover-rsync-tls script
  mover-rsync-tls/server.sh
Labels: lgtm, approved, size/S, ok-to-test

#1118 [release-0.9] Cherry-pick: Merge pull request #1104 from winkrs/add-ipv6-checker
  mover-rsync-tls/server.sh
Labels: lgtm, approved, size/S

#1121 docs - pvc annotations for copy triggers
  docs/usage/index.rst
  docs/usage/pvccopytriggers.rst
Labels: lgtm, approved, size/L

#1114 Release 0.8 golangv1.21, versioning for v0.8.1
  .github/workflows/operator.yml
  Dockerfile
  Dockerfile.volsync-custom-scorecard-tests
  bundle/manifests/volsync.clusterserviceversion.yaml
  go.mod
  go.sum
  version.mk
Labels: lgtm, approved, size/L

#1144 Remove some older kube versions from test matrix
  .github/workflows/operator.yml
Labels: lgtm, approved, size/S
