Repository backube/volsync, pull requests merged in 2025-04, with the labels that each got.

#1611 fix restic cache pvc name collisions for src & dst
  CHANGELOG.md
  controllers/mover/restic/mover.go
  controllers/mover/restic/restic_test.go
  test-e2e/test_restic_manual_normal.yml
  test-e2e/test_restic_manual_normal_cleanup_pvcs.yml
  test-e2e/test_restic_manual_normal_longname.yml
Labels: lgtm, approved, size/L

#1605 build aarch64 image
  .github/workflows/operator.yml
  kubectl-volsync/volsync.yaml
Labels: lgtm, approved, size/M, ok-to-test

#1613 push multiarch images to registry
  .github/workflows/operator.yml
  .github/workflows/registry-push.yml
Labels: lgtm, approved, size/M, ok-to-test

#1615 Update release workflow to attach kubectl-volsync for multi-arch
  .github/workflows/release.yml
  .krew.yaml
  Procedures.md
Labels: lgtm, approved, size/M

#1625 gh workflow ffwd to release br
  .github/workflows/operator.yml
Labels: lgtm, approved, size/M

#1629 fix gen-files check for ffwd branch
  .github/workflows/operator.yml
Labels: lgtm, approved, size/XS

#1646 Dockerfile for konflux builds
  .ci-scripts/yamlconfig.yaml
  Dockerfile.rhtap
Labels: lgtm, approved, size/L

#1649 Dockerfile.rhtap add back fix to not strip symbols
  Dockerfile.rhtap
Labels: lgtm, approved, size/XS
